version: '3.5'
services:
  readme.users.mongo:
    image: mongo
    restart: always
    container_name: readme.users.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: readme-users

    ports:
      - 27017:27017

    volumes:
      - readme.mongo.users:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-users --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.user.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@readme.users.mongo:27017/

volumes:
  readme.mongo.users:
