version: '3.9'
services:
  readme.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server
    container_name: "readme.notify.fakesmtp"
    hostname: "fakesmtp"
    ports:
      - "$FIRST_PORT:8025"
      - "$SECOND_PORT:8080"

  readme.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: readme.notify.rabbitmq
    ports:
      - '1088:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  readme.notify.mongodb:
    image: mongo
    container_name: readme.notify.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: readme-notify
    ports:
      - 27020:27017
    volumes:
      - readme.notify.mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.notify.mongodb.ui:
    image: mongo-express
    restart: always
    container_name: readme.notify.mongodb.ui
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@readme.notify.mongodb:27017/

volumes:
  readme.notify.mongodb:
